_target_: diffusion_policy.workspace.train_bet_lowdim_workspace.TrainBETLowdimWorkspace
action_dim: 9
checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    format_str: epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}-val_loss={val_loss:.4f}.ckpt
    k: 15
    mode: max
    monitor_key: val_loss
dataloader:
  batch_size: 64
  num_workers: 4
  persistent_workers: false
  pin_memory: true
  shuffle: true
exp_name: default
horizon: 12
keypoint_dim: 3
keypoint_visible_rate: 1.0
logging:
  group: null
  id: null
  mode: online
  name: 2023.01.07-20.04.42_train_bet_lowdim_kitchen_lowdim
  project: diffusion_policy_debug
  resume: true
  tags:
  - train_bet_lowdim
  - kitchen_lowdim
  - default
multi_run:
  run_dir: data/outputs/2023.01.07/20.04.42_train_bet_lowdim_kitchen_lowdim
  wandb_name_base: 2023.01.07-20.04.42_train_bet_lowdim_kitchen_lowdim
n_action_steps: 1
n_latency_steps: 0
n_obs_steps: 10
name: train_bet_lowdim
obs_as_global_cond: false
obs_as_local_cond: false
obs_dim: 60
optimizer:
  betas:
  - 0.9
  - 0.95
  learning_rate: 0.0001
  weight_decay: 0.1
past_action_visible: false
policy:
  _target_: diffusion_policy.policy.bet_lowdim_policy.BETLowdimPolicy
  action_ae:
    _target_: diffusion_policy.model.bet.action_ae.discretizers.k_means.KMeansDiscretizer
    action_dim: 9
    num_bins: 64
    predict_offsets: true
  horizon: 12
  n_action_steps: 1
  n_obs_steps: 10
  obs_encoding_net:
    _target_: torch.nn.Identity
    output_dim: 60
  state_prior:
    _target_: diffusion_policy.model.bet.latent_generators.mingpt.MinGPT
    action_dim: 9
    block_size: 12
    discrete_input: false
    focal_loss_gamma: 2.0
    input_dim: 60
    n_embd: 120
    n_head: 6
    n_layer: 6
    offset_loss_scale: 1000.0
    predict_offsets: true
    vocab_size: 64
pred_action_steps_only: false
task:
  action_dim: 9
  dataset:
    _target_: diffusion_policy.dataset.kitchen_mjl_lowdim_dataset.KitchenMjlLowdimDataset
    dataset_dir: /srv/rl2-lab/flash8/mbronars3/ICLR/dataset/kitchen_demos_multitask
    horizon: 12
    pad_after: 0
    pad_before: 2
    seed: 42
    val_ratio: 0.1
  dataset_dir: /srv/rl2-lab/flash8/mbronars3/ICLR/dataset/kitchen_demos_multitask
  env_runner:
    _target_: diffusion_policy.env_runner.kitchen_lowdim_runner.KitchenLowdimRunner
    dataset_dir: /srv/rl2-lab/flash8/mbronars3/ICLR/dataset/kitchen
    fps: 12.5
    max_steps: 280
    n_action_steps: 1
    n_envs: null
    n_obs_steps: 10
    n_test: 50
    n_test_vis: 4
    n_train: 6
    n_train_vis: 2
    past_action: false
    render_hw:
    - 240
    - 360
    test_start_seed: 100000
    train_start_seed: 0
  keypoint_dim: 3
  name: kitchen_lowdim
  obs_dim: 60
task_name: kitchen_lowdim
training:
  checkpoint_every: 25
  debug: false
  device: cuda:0
  enable_normalizer: true
  grad_norm_clip: 1.0
  gradient_accumulate_every: 1
  lr_scheduler: cosine
  lr_warmup_steps: 500
  max_train_steps: null
  max_val_steps: null
  num_epochs: 8000
  resume: true
  rollout_every: 25
  sample_every: 5
  seed: 42
  tqdm_interval_sec: 1.0
  val_every: 1
val_dataloader:
  batch_size: 64
  num_workers: 4
  persistent_workers: false
  pin_memory: true
  shuffle: false